---
jobs:
- name: job
  public: true
  plan:
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: docker.comcast.net/busybox }
      run:
        path: echo
        args: ["Hello world!"]
